[global]
prefix = "iox2_"
# root-path = "/tmp/iceoryx2"

[global.service]
directory = "services"
creation-timeout = { secs = 0, nanos = 500_000_000 }

[global.node]
cleanup-dead-nodes-on-creation = true
cleanup-dead-nodes-on-destruction = true

[defaults.publish-subscribe]
max-publishers = 2
max-subscribers = 8
max-nodes = 20
subscriber-max-buffer-size = 2
publisher-max-loaned-samples = 2
publisher-history-size = 0
enable-safe-overflow = true
unable-to-deliver-strategy = "Block"
