[package]
name = "gui"
version = "0.1.0"
edition = "2024"
authors = ["José Ángel"]
repository = "https://github.com/gelanchez/crazyflie-tfm"
description = "GUI interface for the CrazyFlie"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
egui_extras = { workspace = true }
iceoryx2 = { workspace = true }
types = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
