[workspace]
members = ["control", "gui", "types"]
resolver = "3"

[workspace.dependencies]
eframe = "0.34.1"
egui = "0.34.1"
egui_extras = "0.34.1"
iceoryx2 = "0.8.1"
rand = "0.10.1"
types = { path = "types" }
tokio = { version = "1.52.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
crazyflie-lib = { path = "../../PUBLIC/crazyflie-lib-rs" }
crazyflie-link = { path = "../../PUBLIC/crazyflie-link-rs/crazyflie-link" }
async-trait = "0.1"
flume = "0.11"
byteorder = "1.5"

[patch.crates-io]
crazyflie-link = { path = "../../PUBLIC/crazyflie-link-rs/crazyflie-link" }
