[package]
name = "control"
version = "0.1.0"
edition = "2024"
authors = ["José Ángel"]
repository = "https://github.com/gelanchez/crazyflie-tfm"
description = "Controller for the CrazyFlie system"

[dependencies]
iceoryx2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
types = { workspace = true }
rand = { workspace = true }
crazyflie-lib = { workspace = true }
crazyflie-link = { workspace = true }
async-trait = { workspace = true }
flume = { workspace = true }
byteorder = { workspace = true }
